
kind: pipeline
name: Build and Push

steps:

- name: Build and Push
  image: plugins/docker
  pull: always
  settings:
    repo: ludx/particl-market-ci
    dockerfile: Dockerfile.ci
    username:
      from_secret: REGISTRY_USER
    password:
      from_secret: REGISTRY_PASSWORD
    debug: true
    tags:
      - latest
      - ${DRONE_COMMIT_SHA}

# TODO: caching
# - https://github.com/drone-plugins/drone-docker/issues/172
# - https://discourse.drone.io/t/how-do-i-cache-node-modules-between-builds/1946/2

- name: Unit test
  image: docker:dind
  commands:
    - docker login ${REGISTRY} -u ${REGISTRY_USER} -p ${REGISTRY_PASS}
    - docker run --name testapp ludx/particl-market-ci:${DRONE_COMMIT_SHA} bin/ci-unit-tests.sh




# pipeline describes build steps
#pipeline:
    # every entry in the pipeline describes a single build step
#    build_image:
#        image: node
#        environment:
#            VERSION: "${DRONE_TAG}"
#            COMMIT: "${DRONE_COMMIT_SHA:0:7}"

        # commands executed in the container
#        commands:
#            - ./bin/ci-post.sh "[$CIRCLE_BRANCH] Building $CIRCLE_BUILD_URL" "CircleCI" "$DISCORD_URL"
#            - ./bin/ci-create-build-version.sh
#            - docker login $REGISTRY -u $REGISTRY_USER -p $REGISTRY_PASS
#            - docker build --pull --cache-from "$IMAGE_NAME" --tag "$REGISTRY/$IMAGE_NAME:$CIRCLE_SHA1" -f Dockerfile.ci .
#            - docker push $REGISTRY/$IMAGE_NAME:$CIRCLE_SHA1
