
workspace:
  base: /workspace      # shared base volume available to all pipeline steps.
  path: particl-market  # default working directory, where your code is cloned


kind: pipeline
name: Build and Push

steps:

- name: restore cache
  image: drillster/drone-volume-cache
  restore: true         # instruct plugin to restore cache, can be true or false
  mount:                # list of folders or files to cache
    - node_modules
  ttl: 10               # maximum cache lifetime in days
  volumes:              # mount the cache volume, needs "trusted"
    - name: cache
      path: /cache

- name: build and push image
  image: plugins/docker
  pull: always
  settings:
    repo: ludx/particl-market-ci
    dockerfile: Dockerfile.ci
    username:
      from_secret: REGISTRY_USER
    password:
      from_secret: REGISTRY_PASSWORD
    debug: true
    tags:
      - latest
      - ${DRONE_COMMIT_SHA}


# TODO: caching
# - https://github.com/drone-plugins/drone-docker/issues/172
# - https://discourse.drone.io/t/how-do-i-cache-node-modules-between-builds/1946/2

- name: run unit tests
  image: ludx/particl-market-ci:${DRONE_COMMIT_SHA}
  volumes:              # mount an absolute path on the host machine into a pipeline step
    - name: node_modules
      path: /app/node_modules
  commands:
    - echo "workspace:"
    - ls -al /workspace
    - ls -al /workspace/particl-market
    - bin/ci-unit-tests.sh

# cache files and directories between builds
- name: rebuild cache
  image: drillster/drone-volume-cache
  rebuild: true         # instruct plugin to rebuild cache, can be true or false
  mount:                # list of folders or files to cache
    - node_modules
  volumes:              # mount the cache volume, needs "trusted"
    - name: cache
      path: /cache


volumes:
- name: node_modules
  host:
    path: ./node_modules
- name: cache
  host:
      path: /tmp/cache

#- name: test
#  image: docker
#  environment:
#      DOCKER_HOST: unix:///drone/docker.sock
#      DOCKER_USER:
#          from_secret: REGISTRY_USERNAME
#      DOCKER_PASSWORD:
#          from_secret: REGISTRY_PASSWORD
#      REGISTRY_EMAIL: juha.kovanen@gmail.com
#  commands:
#  - sleep 10 # gives docker enough time to initialize
#  - echo $DOCKER_USER
#  - echo $DOCKER_PASSWORD
#  - docker login -u ${REGISTRY_USERNAME} -p ${REGISTRY_PASSWORD}
#  - docker run --name testapp ludx/particl-market-ci:${DRONE_COMMIT_SHA} bin/ci-unit-tests.sh
#
#services:
#- name: docker
#  image: docker:dind
#  privileged: true
#  command: [ '-H', 'unix:///drone/docker.sock' ]

# pipeline describes build steps
#pipeline:
    # every entry in the pipeline describes a single build step
#    build_image:
#        image: node
#        environment:
#            VERSION: "${DRONE_TAG}"
#            COMMIT: "${DRONE_COMMIT_SHA:0:7}"

        # commands executed in the container
#        commands:
#            - ./bin/ci-post.sh "[$CIRCLE_BRANCH] Building $CIRCLE_BUILD_URL" "CircleCI" "$DISCORD_URL"
#            - ./bin/ci-create-build-version.sh
#            - docker login $REGISTRY -u $REGISTRY_USER -p $REGISTRY_PASS
#            - docker build --pull --cache-from "$IMAGE_NAME" --tag "$REGISTRY/$IMAGE_NAME:$CIRCLE_SHA1" -f Dockerfile.ci .
#            - docker push $REGISTRY/$IMAGE_NAME:$CIRCLE_SHA1
